### PR TITLE
Work in Progress: Remove redundant entries

### PR DESCRIPTION
**Pull request by iam-py-test**
This PR removes a few redundant entries from your lists
Please do not merge it as I am still working on this

### CODE REVIEW

**Comment by iam-py-test** [comment]
For some reason it tells me that my script added content, but the diff is too big for GH or the Linux diff command

**Comment by thomasmerz** [comment]
This removal of duplicates should be done by a script. Has it been done by a script?

**Comment by thomasmerz** [comment]
The only additional line is this one:

image

Complete:

image

**Comment by iam-py-test** [comment]
I think I should close this & either I can redo this or you can.

**Comment by iam-py-test** [comment]
> This removal of duplicates should be done by a script. Has it been done by a script?

I don't remember. Sorry

**Pull request closed without merging**
